name=mongodb_usuario_source
connector.class=com.mongodb.kafka.connect.MongoSourceConnector
tasks.max=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
connection.uri=mongodb://cesar:cesar@mongodb:27017/DevDemo?retryWrites=true&loadBalanced=false&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
database=DevDemo
collection=Usuarios
topic.namespace.map={"*":"sample.usuarios"}
copy.existing=true
publish.full.document.only=true
